// Generated by CoffeeScript 1.8.0
(function() {
  var Maze, Piece, maze;

  Piece = (function() {

    /*
    * the part of maze, a maze is expecting to have 15 pieces
    * @param col: the column position of piece
    * @param row: the row position of piece
    * @param id: the number of the piece, used as an identity(one and only)
    * @param element: the element belong to specific piece in DOM tree
     */
    function Piece(col, row, id, element) {
      this.col = col;
      this.row = row;
      this.id = id;
      this.element = element;
    }

    return Piece;

  })();

  Maze = (function() {

    /*
    * maze, which would encapsulate some essential methods
    * @param pieces: the array that contain all of the piece in maze
    * @param blankCol: recording the column position of blank in maze
    * @param @blankRow: recording the row position of blank in maze
     */
    function Maze(pieces, blankCol, blankRow) {
      this.pieces = pieces != null ? pieces : [];
      this.blankCol = blankCol != null ? blankCol : 4;
      this.blankRow = blankRow != null ? blankRow : 4;
    }


    /*
    * push a piece into pieces array
    * @param piece: the piece to push(class Piece)
     */

    Maze.prototype.push = function(piece) {
      return this.pieces.push(piece);
    };


    /*
    * initialize maze
    * initialize dataStructure
    * initialize DOM element
    * add event listener for events
     */

    Maze.prototype.initialize = function() {
      var ele, that;
      this.initializeDataStructure();
      this.initializePieceElement();
      this.updatePosition();
      that = this;
      document.getElementById('shufflebutton').addEventListener('click', function() {
        return that.shuffle(that);
      });
      ele = document.getElementById('background-image');
      return ele.onchange = function() {
        return that.changeBackground(ele);
      };
    };


    /*
    * initialize dataStructure of maze
    * for each step in loop, create a piece(class Piece), and push to pieces
    * add event handler to piece
     */

    Maze.prototype.initializeDataStructure = function() {
      var col, ele, onePiece, piece, pieces, row, that, _results;
      col = 1;
      pieces = document.getElementById('puzzlearea').getElementsByTagName('div');
      _results = [];
      while (col < 5) {
        row = 1;
        while (row < 5) {
          piece = new Piece(col, row, (col - 1) * 4 + row, pieces[(col - 1) * 4 + row - 1]);
          if (piece.element !== void 0) {
            this.push(piece);
            onePiece = this.pieces[(col - 1) * 4 + row - 1];
            that = this;
            ele = onePiece.element;

            /*
            * in order to let all DOM element binding to their own piece, use a closure
            * 'that' is maze, so that the function pieceClickHandler could execute in maze's action scope
            * @param ele: the DOM element for piece
             */
            onePiece.element.onclick = (function(ele) {
              return function() {
                return that.pieceClickHandler(ele);
              };
            })(ele);
          }
          row++;
        }
        _results.push(col++);
      }
      return _results;
    };


    /*
    * initialize DOM element for piece
     */

    Maze.prototype.initializePieceElement = function() {
      var piece, _i, _len, _ref, _results;
      _ref = this.pieces;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        piece = _ref[_i];
        if (piece.element !== void 0) {
          _results.push(piece.element.style.backgroundPosition = -(piece.row - 1) * 100 + "px " + -(piece.col - 1) * 100 + "px");
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };


    /*
    * update exactly where piece is in browser(syncing data and view)
     */

    Maze.prototype.updatePosition = function() {
      var piece, _i, _len, _ref, _results;
      _ref = this.pieces;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        piece = _ref[_i];
        if (piece.element !== void 0) {
          piece.element.style.left = (piece.row - 1) * 100 + "px";
          piece.element.style.top = (piece.col - 1) * 100 + "px";
          if (Math.abs(piece.row - this.blankRow) + Math.abs(piece.col - this.blankCol) > 1) {
            _results.push(piece.element.className = 'puzzlepiece');
          } else {
            _results.push(piece.element.className = 'puzzlepiece movablepiece');
          }
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };


    /*
    * event handler for click event for piece in maze
    * @param ele: the DOM element for piece
     */

    Maze.prototype.pieceClickHandler = function(ele) {
      var index;
      index = parseInt(ele.textContent);
      if (Math.abs(this.pieces[index - 1].row - this.blankRow) + Math.abs(this.pieces[index - 1].col - this.blankCol) <= 1) {
        this.move(index);
        this.updatePosition();
        if (this.completed()) {
          return alert('You Win!');
        }
      }
    };


    /*
    * exchange pieces[index - 1] position data with blank position
    * @param index: recording which piece to exchange, stand for the postion(index - 1) in pieces array
     */

    Maze.prototype.move = function(index) {
      this.pieces[index - 1].col ^= this.blankCol;
      this.blankCol ^= this.pieces[index - 1].col;
      this.pieces[index - 1].col ^= this.blankCol;
      this.pieces[index - 1].row ^= this.blankRow;
      this.blankRow ^= this.pieces[index - 1].row;
      return this.pieces[index - 1].row ^= this.blankRow;
    };


    /*
    * judge whether the maze has been completed
     */

    Maze.prototype.completed = function() {
      var index;
      index = 1;
      while (index <= 15) {
        if ((this.pieces[index - 1].col - 1) * 4 + this.pieces[index - 1].row !== this.pieces[index - 1].id) {
          return false;
        }
        index++;
      }
      return true;
    };


    /*
    * shuffle the maze randomly
    * @param that: the maze, cuz when in click event, 'this' is DOM event, not maze
     */

    Maze.prototype.shuffle = function(that) {
      var changeCol, movingUp, times;
      times = 100;
      while (times > 0) {
        changeCol = Math.round(Math.random());
        movingUp = Math.round(Math.random());
        that.randomMove(changeCol, movingUp);
        times--;
      }
      return this.updatePosition();
    };


    /*
    * auto move randomly
    * @param changeCol: random number(0 or 1), deside change in column position(1) or row position(0)
    * @param movingUp: random number(0 or 1), deside moving up(1) or down(0)
     */

    Maze.prototype.randomMove = function(changeCol, movingUp) {
      var col, row;
      col = this.blankCol;
      row = this.blankRow;
      if (changeCol) {
        col = movingUp && this.isValid(col + 1) ? col + 1 : this.isValid(col - 1) ? col - 1 : col;
      } else {
        row = movingUp && this.isValid(row + 1) ? row + 1 : this.isValid(row - 1) ? row - 1 : row;
      }
      if ((col !== this.blankCol || row !== this.blankRow) && (col - 1) * 4 + row !== 16) {
        return this.move((col - 1) * 4 + row);
      }
    };


    /*
    * judge whether the position is a valid one
    * @param position: position to judge
     */

    Maze.prototype.isValid = function(position) {
      if (position >= 1 && position <= 4) {
        return true;
      } else {
        return false;
      }
    };


    /*
    * change background image
    * @param ele: the DOM element for the selected
     */

    Maze.prototype.changeBackground = function(ele) {
      var piece, _i, _len, _ref, _results;
      _ref = this.pieces;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        piece = _ref[_i];
        _results.push(piece.element.style.backgroundImage = 'url(' + ele.value + ')');
      }
      return _results;
    };

    return Maze;

  })();

  maze = new Maze;


  /*
  * initialize maze when window is loaded
   */

  window.onload = function() {
    return maze.initialize();
  };

}).call(this);
